pub mod AccessErrors {
    pub const INVALID_MINTER: felt252 = 'INVALID_MINTER_ADDRESS';
    pub const INVALID_TOKEN: felt252 = 'INVALID_TOKEN_ADDRESS';
    pub const CALLER_MISSING_ROLE: felt252 = 'CALLER_IS_MISSING_ROLE';
    pub const ZERO_ADDRESS: felt252 = 'INVALID_ACCOUNT_ADDRESS';
    pub const ALREADY_INITIALIZED: felt252 = 'ROLES_ALREADY_INITIALIZED';
    pub const ZERO_ADDRESS_GOV_ADMIN: felt252 = 'ZERO_PROVISIONAL_GOV_ADMIN';
    pub const ONLY_APP_GOVERNOR: felt252 = 'ONLY_APP_GOVERNOR';
    pub const ONLY_OPERATOR: felt252 = 'ONLY_OPERATOR';
    pub const ONLY_TOKEN_ADMIN: felt252 = 'ONLY_TOKEN_ADMIN';
    pub const ONLY_UPGRADE_GOVERNOR: felt252 = 'ONLY_UPGRADE_GOVERNOR';
    pub const ONLY_SECURITY_ADMIN: felt252 = 'ONLY_SECURITY_ADMIN';
    pub const ONLY_SECURITY_AGENT: felt252 = 'ONLY_SECURITY_AGENT';
    pub const ONLY_MINTER: felt252 = 'MINTER_ONLY';
    pub const ONLY_SELF_CAN_RENOUNCE: felt252 = 'ONLY_SELF_CAN_RENOUNCE';
    pub const GOV_ADMIN_CANNOT_RENOUNCE: felt252 = 'GOV_ADMIN_CANNOT_SELF_REMOVE';
}
