pub const APPROVAL_ALREADY_REGISTERED: felt252 = 'APPROVAL_ALREADY_REGISTERED';
pub const APPROVAL_NOT_REGISTERED: felt252 = 'APPROVAL_NOT_REGISTERED';
pub const CALLER_IS_NOT_OWNER_ACCOUNT: felt252 = 'CALLER_IS_NOT_OWNER_ACCOUNT';
pub const INVALID_STATUS: felt252 = 'INVALID_STATUS';
pub const DEPOSIT_ALREADY_PROCESSED: felt252 = 'DEPOSIT_ALREADY_PROCESSED';
