pub const APPROVAL_ALREADY_REGISTERED: felt252 = 'APPROVAL_ALREADY_REGISTERED';
pub const APPROVAL_NOT_REGISTERED: felt252 = 'APPROVAL_NOT_REGISTERED';
pub const CALLER_IS_NOT_OWNER_ACCOUNT: felt252 = 'CALLER_IS_NOT_OWNER_ACCOUNT';
pub const INVALID_STATUS: felt252 = 'INVALID_STATUS';
pub const REQUEST_ALREADY_DONE: felt252 = 'REQUEST_ALREADY_DONE';
