pub mod ReplaceErrors {
    pub const FINALIZED: felt252 = 'FINALIZED';
    pub const UNKNOWN_IMPLEMENTATION: felt252 = 'UNKNOWN_IMPLEMENTATION';
    pub const NOT_ENABLED_YET: felt252 = 'NOT_ENABLED_YET';
    pub const IMPLEMENTATION_EXPIRED: felt252 = 'IMPLEMENTATION_EXPIRED';
    pub const EIC_LIB_CALL_FAILED: felt252 = 'EIC_LIB_CALL_FAILED';
    pub const REPLACE_CLASS_HASH_FAILED: felt252 = 'REPLACE_CLASS_HASH_FAILED';
}
