name: Pull Request Integration

on:
  pull_request:
    branches:
      - main

jobs:
  runs-on: namespace-profile-starkware-libs-starknet-staking-large-ubuntu-24-04-amd64

  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit

  check_formatting:
    uses: ./.github/workflows/check_formatting.yaml
